/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatInput: typeof import('./components/ChatInput.vue')['default']
    ChatMessage: typeof import('./components/ChatMessage.vue')['default']
    FilePreview: typeof import('./components/FilePreview.vue')['default']
    ImageGallery: typeof import('./components/ImageGallery.vue')['default']
    ImageLightbox: typeof import('./components/ImageLightbox.vue')['default']
    ImagePreviewStrip: typeof import('./components/ImagePreviewStrip.vue')['default']
    MessageMedia: typeof import('./components/MessageMedia.vue')['default']
    TypingIndicator: typeof import('./components/TypingIndicator.vue')['default']
    UploadProgress: typeof import('./components/UploadProgress.vue')['default']
    UsernameModal: typeof import('./components/UsernameModal.vue')['default']
    VoiceMessage: typeof import('./components/VoiceMessage.vue')['default']
    VoiceRecorder: typeof import('./components/VoiceRecorder.vue')['default']
  }
}
